
create PROCEDURE [dbo].[PROC_INTEGRACAO_LINX_WISE_PRODUTOS]      
 --@prCapanha INT = NULL  

AS

-- #GS:02.11# - Silvio Luiz - 11/10/2021 - Inclusão tabela de preço VF da MF
-- #GS:02.10# - Guilherme Rocha - 06/10/2021 - Ajustado o delete dos códigos de preços de produtos e da classificação fiscal.
-- #GS:02.09# - Guilherme Rocha - 06/10/2021 - Retornado o código de insert anterior do PRODUTOS_PRECOS. Removido o trecho do JSON.
-- #GS:02.08# - Silvio Luiz - 28/09/2021 - Inclusão tabela de preço VO da MF
-- #GS:02.07# - Silvio Luiz - 28/09/2021 - Inclusão para integrar as colunas DESC_COMPOSICAO E LINHA_MF
-- #GS:02.06# - Silvio Luiz - 30/05/2020 - Inclusão para integrar as colunas PS.DESC_PRODUTO_SEGMENTO, PSO.DESC_PRODUTO_SOLUCAO,PC.COORDENADO
-- #GS:02.01# - Silvio Luiz - 29/04/2020 - Tratamento para deletar somente o id_campanha ativo da Cris Barros
-- #GS:01.05# - Marco Banaggia - 07/01/2020 - Retirado novamente o truncate das tabelas muro antes da atualização, foi colocado para realizar um backup antes.
-- #GS:01.04# - Marco Banaggia - 26/09/2019 - Ajustes dos campos para melhorar perfomace.
-- #GS:01.03# - Marco Banaggia - 23/07/2019 - Inclusão do preenchimento da tabela de Propriedades do Produto para atender o Mel Leva
-- #GS:01.02# - Marco Banaggia - 22/07/2019 - Inclusão para levar as classificações Fiscais que contem IPI
-- 07/06/2018 - LPR - #GS:01.01# - ATUALIZANDO O CODIGO: SOLICITAÇÃO DO BANAGGIA.  
-- 07/05/2018 - LPR - #GS:01.01# - RETIRANDO AS VARIAVEIS E RETIRANDO O ERRO:Ambiguous column name 'COLECAO'.  
-- 07/05/2018 - LPR - #GS:01.00# - CRIANDO O OBJETO PARA ATENDER PROJETO WISE. INTEGRAÇÃO DOS CLIENTES  

SET NOCOUNT ON   

DECLARE  @TABELA varchar(500), @TABELA_OLD VARCHAR(500), @CAMPANHA VARCHAR(500) 

CREATE TABLE #TABELAS (TABELA VARCHAR(100), TABELA_BKP VARCHAR(100),PROCESSADO BIT, ERROR VARCHAR(500))


-- truncate table GS_WETL_REPOSITORIO
-- select * from GS_WETL_REPOSITORIO
 
 --- CARREGANDO PRODUTOS COM AJUSTE DE COLECAO PARA SER USADO NAS CONSULTAS ----- TABELA: ##PRODUTOS_INTERNET
EXEC PROC_SELECIONA_PRODUTOS_LINX_WISE
  
DECLARE   
   --@Conteudo Varchar(200),  
   --@WhereProdutos Varchar(MAX),  
   @strSql Varchar(MAX),
   @TSQL VARCHAR(MAX) 
  
----#GS:01.05# - Retirado pois e feito um backup das tabelas antes derealizar o Truncate
 -- Limpa Tabelas de Muro  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTOS]')    AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_CORES_BASICAS]')  AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTO_CORES]')  AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTOS_BARRA]')  AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTOS_PRECOS]')  AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTOS_TAMANHOS]') AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PRODUTOS_PRECO_COR]') AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_PROP_PRODUTOS]')  AT WISE_AZURE  
--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]')  AT WISE_AZURE 
  
  -- PRODUTOS - Monta Select e executa insert   
 
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_PRODUTOS','WS_PRODUTOS_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PRODUTOS')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PRODUTOS]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PRODUTOS]') AT WISE_AZURE

 SET @TSQL = ''
 DECLARE @StrAgg_ID_CAMPANHA VARCHAR(MAX) = ''
 SELECT @StrAgg_ID_CAMPANHA = ISNULL(STUFF(
                                             (SELECT ',' + CONVERT(VARCHAR(MAX), t.ID_CAMPANHA)
                                                FROM (SELECT DISTINCT ISNULL(ID_CAMPANHA, '') AS ID_CAMPANHA
                                                        FROM WS_PRODUTOS_INTERNET) AS t
                                                 FOR XML PATH('')
                                             ), 
                                           1, LEN(','), ''), '0')


 SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 EXEC (@TSQL)

	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
 
     SELECT @strSql = '    
     INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTOS   
             (PRODUTO, REFER_FABRICANTE, CLASSIF_FISCAL, PERIODO_PCP, TIPO_PRODUTO, DT_EXCLUSAO, COD_CATEGORIA,
				FABRICANTE, DESC_PRODUTO, GRUPO_PRODUTO, SUBGRUPO_PRODUTO, DESC_PROD_NF, GRIFFE, LINHA, GRADE, OBS,
				STATUS_PRODUTO, VARIA_PRECO_COR, ESTILISTA, DT_INTEGRACAO, ID_CAMPANHA, REDE_LOJAS, COLECAO, SEXO_TIPO, DESC_PRODUTO_SEGMENTO, DESC_PRODUTO_SOLUCAO, COORDENADO,
				DESC_COMPOSICAO, LINHA_MF,ENVIA_ATACADO_INTERNET,ENVIA_FRANQUIA_INTERNET)  


 SELECT 
		PRODUTOS.PRODUTO,
		PRODUTOS.REFER_FABRICANTE, PRODUTOS.CLASSIF_FISCAL, PRODUTOS.PERIODO_PCP, PRODUTOS.TIPO_PRODUTO,
		NULL DT_EXCLUSAO, PRODUTOS.COD_CATEGORIA, PRODUTOS.FABRICANTE, PRODUTOS.DESC_PRODUTO, PRODUTOS.GRUPO_PRODUTO,
		PRODUTOS.SUBGRUPO_PRODUTO, PRODUTOS.DESC_PROD_NF, PRODUTOS.GRIFFE, PRODUTOS.LINHA, PRODUTOS.GRADE, PRODUTOS.OBS,
		PRODUTOS.STATUS_PRODUTO, PRODUTOS.VARIA_PRECO_COR, PRODUTOS.ESTILISTA, GETDATE() DT_INTEGRACAO, 
		WS.ID_CAMPANHA,
		PRODUTOS.REDE_LOJAS, PRODUTOS.COLECAO, SEXO_TIPO, PS.DESC_PRODUTO_SEGMENTO, PSO.DESC_PRODUTO_SOLUCAO
		, PG.SUBCATEGORIA_PRODUTO AS COORDENADO
		, MC.DESC_COMPOSICAO
		, PP.VALOR_PROPRIEDADE AS LINHA_MF
		, PRODUTOS.ENVIA_ATACADO_INTERNET AS ENVIA_ATACADO_INTERNET
		, ISNULL(PRODUTOS.ENVIA_FRANQUIA_INTERNET,0) AS ENVIA_FRANQUIA_INTERNET
		FROM PRODUTOS (NOLOCK) 
		INNER JOIN WS_PRODUTOS_INTERNET WS ON PRODUTOS.PRODUTO = WS.PRODUTO
		LEFT JOIN PRODUTOS_SEGMENTO PS ON PRODUTOS.COD_PRODUTO_SEGMENTO = PS.COD_PRODUTO_SEGMENTO
		LEFT JOIN PRODUTOS_SOLUCAO PSO ON PRODUTOS.COD_PRODUTO_SOLUCAO = PSO.COD_PRODUTO_SOLUCAO
		LEFT JOIN PRODUTOS_CATEGORIA PT ON PRODUTOS.COD_CATEGORIA = PT.COD_CATEGORIA
		LEFT JOIN PRODUTOS_SUBCATEGORIA PG ON PRODUTOS.COD_SUBCATEGORIA = PG.COD_SUBCATEGORIA AND PG.COD_CATEGORIA = PRODUTOS.COD_CATEGORIA
		LEFT JOIN MATERIAIS_COMPOSICAO MC ON PRODUTOS.COMPOSICAO=MC.COMPOSICAO
		LEFT JOIN PROP_PRODUTOS PP ON PP.PRODUTO=WS.PRODUTO AND PP.PROPRIEDADE = ''00812''
		'  
  
     EXECUTE(@strSql)  

	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH





     --PRODUTOS CORES - Monta select e insere  
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_PRODUTO_CORES','WS_PRODUTO_CORES_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PRODUTO_CORES')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PRODUTO_CORES]')	AT WISE_AZURE

 SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTO_CORES] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 EXEC (@TSQL)

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PRODUTO_CORES]') AT WISE_AZURE  
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTO_CORES] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)

     SELECT @strSql =  '  
     INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTO_CORES (
			 PRODUTO,DESC_COR_PRODUTO,PRODUTO,COR_PRODUTO,FIM_VENDAS,DT_EXCLUSAO, WS.ID_CAMPANHA, LIBERAR_GRADE_WEB)  
	SELECT
		PRODUTO_CORES.PRODUTO,PRODUTO_CORES.DESC_COR_PRODUTO,PRODUTO_CORES.PRODUTO,PRODUTO_CORES.COR_PRODUTO,PRODUTO_CORES.FIM_VENDAS,NULL AS DT_EXCLUSAO,WS.ID_CAMPANHA, PRODUTO_CORES.LIBERAR_GRADE_WEB
	FROM 
		PRODUTO_CORES (NOLOCK) 
		INNER JOIN WS_PRODUTOS_INTERNET WS ON PRODUTO_CORES.PRODUTO = WS.PRODUTO
	WHERE 
		ISNULL(STATUS_VENDA_ATUAL,1)=1
     '  
     EXECUTE(@strSql)  
  
	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

      
  -- CORES BÁSICAS  
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_CORES_BASICAS','WS_CORES_BASICAS_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_CORES_BASICAS')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_CORES_BASICAS]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_CORES_BASICAS]') AT WISE_AZURE
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CORES_BASICAS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
 
 SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CORES_BASICAS] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 EXEC (@TSQL)

 
  --INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_CORES_BASICAS (COR, DESC_COR, ID_CAMPANHA)  
  -- SELECT A.COR, A.DESC_COR,B.ID_CAMPANHA  
  --  FROM CORES_BASICAS A WITH (NOLOCK)  
		--JOIN GS_CAMPANHA_ATACADO (NOLOCK) B ON B.COLECAO_ATIVA = 1
  --	WHERE A.USO_PRODUTOS=1 AND A.DESC_COR <> 'COD DISPONIVEL'
 

  EXEC ('
  IF OBJECT_ID(''SOMA_LINX.DBO.WS_CORES_BASICAS_JsonTmp'') IS NOT NULL 
    DROP TABLE SOMA_LINX.DBO.WS_CORES_BASICAS_JsonTmp; 
  CREATE TABLE SOMA_LINX.DBO.WS_CORES_BASICAS_JsonTmp (Col1 VARCHAR(MAX));
  ') 
  AT WISE_AZURE;

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT A.COR, A.DESC_COR,B.ID_CAMPANHA  
                 FROM CORES_BASICAS A WITH (NOLOCK)  
		               JOIN GS_CAMPANHA_ATACADO (NOLOCK) B ON B.COLECAO_ATIVA = 1
  	             WHERE A.USO_PRODUTOS=1 AND A.DESC_COR <> ''COD DISPONIVEL''
                  FOR JSON PATH);

  INSERT INTO [WISE_AZURE].SOMA_LINX.DBO.WS_CORES_BASICAS_JsonTmp(Col1)
  VALUES (@json);
  '
  EXEC (@TSQL)

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT Col1 FROM SOMA_LINX.DBO.WS_CORES_BASICAS_JsonTmp)

  INSERT INTO [Soma_Linx].[dbo].WS_CORES_BASICAS (COR, DESC_COR, ID_CAMPANHA) 
  SELECT COR, DESC_COR, ID_CAMPANHA
  FROM OPENJSON(@json) 
  WITH (
    COR CHAR(10), 
    DESC_COR VARCHAR(25), 
    ID_CAMPANHA INT
    )
  '
  EXEC (@TSQL) AT [WISE_AZURE]


	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH


    -- LPR - RETIRANDO O JOIN COM A TABELA MURO  
    --INNER JOIN WS_PRODUTO_CORES B WITH (NOLOCK)  
    -- ON B.COR = A.COR  
     
  -- PRODUTOS TAMANHOS  
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_PRODUTOS_TAMANHOS','WS_PRODUTOS_TAMANHOS_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PRODUTOS_TAMANHOS')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PRODUTOS_TAMANHOS]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PRODUTOS_TAMANHOS]') AT WISE_AZURE 
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_TAMANHOS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) 

 SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_TAMANHOS] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 EXEC (@TSQL)

	INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTOS_TAMANHOS (GRADE, NUMERO_TAMANHOS, NUMERO_QUEBRAS, QUEBRA_1, QUEBRA_2, QUEBRA_3, QUEBRA_4, QUEBRA_5, TAMANHO_1, TAMANHO_2,   
			TAMANHO_3, TAMANHO_4, TAMANHO_5, TAMANHO_6, TAMANHO_7, TAMANHO_8, TAMANHO_9, TAMANHO_10, TAMANHO_11, TAMANHO_12,  
			TAMANHO_13, TAMANHO_14, TAMANHO_15, TAMANHO_16, GRADE_BASE, TAMANHOS_DIGITADOS, GRADE_CODIGO, DATA_PARA_TRANSFERENCIA,ID_CAMPANHA)  
	SELECT A.GRADE, A.NUMERO_TAMANHOS, A.NUMERO_QUEBRAS, A.QUEBRA_1, A.QUEBRA_2, A.QUEBRA_3, A.QUEBRA_4, A.QUEBRA_5, A.TAMANHO_1, A.TAMANHO_2,  
		A.TAMANHO_3, A.TAMANHO_4, A.TAMANHO_5, A.TAMANHO_6, A.TAMANHO_7, A.TAMANHO_8, A.TAMANHO_9, A.TAMANHO_10, A.TAMANHO_11, A.TAMANHO_12,  
		A.TAMANHO_13, A.TAMANHO_14, A.TAMANHO_15, A.TAMANHO_16, A.GRADE_BASE, A.TAMANHOS_DIGITADOS, A.GRADE_CODIGO, A.DATA_PARA_TRANSFERENCIA,B.ID_CAMPANHA  
	FROM PRODUTOS_TAMANHOS A WITH (NOLOCK)   
		JOIN GS_CAMPANHA_ATACADO (NOLOCK) B ON B.COLECAO_ATIVA = 1

	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

      
-- PRODUTOS BARRAS  
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_PRODUTOS_BARRA','WS_PRODUTOS_BARRA_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PRODUTOS_BARRA')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PRODUTOS_BARRA]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PRODUTOS_BARRA]') AT WISE_AZURE 
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_BARRA] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
 SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_BARRA] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 EXEC (@TSQL)
 

	--INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTOS_BARRA (CODIGO_BARRA, PRODUTO, COR_PRODUTO, TAMANHO, GRADE, ID_CAMPANHA)  
	--SELECT A.CODIGO_BARRA, A.PRODUTO, A.COR_PRODUTO, A.TAMANHO, A.GRADE, WS.ID_CAMPANHA  
	--FROM PRODUTOS_BARRA A WITH (NOLOCK)   
	--		INNER JOIN PRODUTOS B (NOLOCK) ON A.PRODUTO = B.PRODUTO  AND B.ENVIA_ATACADO_INTERNET = '1' 
	--		INNER JOIN WS_PRODUTOS_INTERNET WS ON B.PRODUTO = WS.PRODUTO
	--WHERE A.INATIVO = 0

  EXEC ('
  IF OBJECT_ID(''SOMA_LINX.DBO.WS_PRODUTOS_BARRA_JsonTmp'') IS NOT NULL 
    DROP TABLE SOMA_LINX.DBO.WS_PRODUTOS_BARRA_JsonTmp; 
  CREATE TABLE SOMA_LINX.DBO.WS_PRODUTOS_BARRA_JsonTmp (Col1 VARCHAR(MAX));
  ') 
  AT WISE_AZURE;

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT A.CODIGO_BARRA, A.PRODUTO, A.COR_PRODUTO, A.TAMANHO, A.GRADE, WS.ID_CAMPANHA  
	               FROM PRODUTOS_BARRA A WITH (NOLOCK)   
			               INNER JOIN PRODUTOS B (NOLOCK) ON A.PRODUTO = B.PRODUTO  AND B.ENVIA_ATACADO_INTERNET = ''1'' 
			               INNER JOIN WS_PRODUTOS_INTERNET WS ON B.PRODUTO = WS.PRODUTO
	               WHERE A.INATIVO = 0
                  FOR JSON PATH);

  INSERT INTO [WISE_AZURE].SOMA_LINX.DBO.WS_PRODUTOS_BARRA_JsonTmp(Col1)
  VALUES (@json);
  '
  EXEC (@TSQL)

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT Col1 FROM SOMA_LINX.DBO.WS_PRODUTOS_BARRA_JsonTmp)

  INSERT INTO [Soma_Linx].[dbo].WS_PRODUTOS_BARRA (CODIGO_BARRA, PRODUTO, COR_PRODUTO, TAMANHO, GRADE, ID_CAMPANHA) 
  SELECT CODIGO_BARRA, PRODUTO, COR_PRODUTO, TAMANHO, GRADE, ID_CAMPANHA
  FROM OPENJSON(@json) 
  WITH (
    CODIGO_BARRA VARCHAR(25), 
    PRODUTO CHAR(12), 
    COR_PRODUTO CHAR(10), 
    TAMANHO INT, 
    GRADE VARCHAR(8), 
    ID_CAMPANHA INT
    )
  '
  EXEC (@TSQL) AT [WISE_AZURE]


	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH
  
-- PREÇOS  
BEGIN TRY 
	INSERT INTO #TABELAS 
	SELECT 'WS_PRODUTOS_PRECOS','WS_PRODUTOS_PRECOS_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PRODUTOS_PRECOS')
	--#GS:02.10#
	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PRODUTOS_PRECOS]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PRODUTOS_PRECOS]') AT WISE_AZURE
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_PRECOS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) 
	SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_PRODUTOS_PRECOS] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
	EXEC (@TSQL)

	--INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTOS_PRECOS (CODIGO_TAB_PRECO,  PRODUTO, PRECO1, PROMOCAO_DESCONTO, ID_CAMPANHA)  
	--SELECT A.CODIGO_TAB_PRECO, A.PRODUTO, A.PRECO1,A.PROMOCAO_DESCONTO,WS.ID_CAMPANHA  
	--FROM PRODUTOS_PRECOS A WITH (NOLOCK)   
	--INNER JOIN (SELECT CODIGO_TAB_PRECO FROM TABELAS_PRECO (NOLOCK) WHERE TABELA LIKE '%ATACADO%') TAB ON TAB.CODIGO_TAB_PRECO = A.CODIGO_TAB_PRECO  
	--INNER JOIN PRODUTOS B (NOLOCK) ON A.PRODUTO = B.PRODUTO 
	--INNER JOIN WS_PRODUTOS_INTERNET WS ON B.PRODUTO = WS.PRODUTO
	
	-- #GS:02.09#
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[dbo].WS_PRODUTOS_PRECOS (CODIGO_TAB_PRECO, PRODUTO, PRECO1, PROMOCAO_DESCONTO, ID_CAMPANHA)
	SELECT A.CODIGO_TAB_PRECO, A.PRODUTO, A.PRECO1,A.PROMOCAO_DESCONTO, WS.ID_CAMPANHA  
	FROM PRODUTOS_PRECOS A WITH (NOLOCK)   
	INNER JOIN (SELECT CODIGO_TAB_PRECO FROM TABELAS_PRECO (NOLOCK) WHERE TABELA LIKE '%ATACADO%' OR CODIGO_TAB_PRECO IN ('VO', 'VF')) TAB ON TAB.CODIGO_TAB_PRECO = A.CODIGO_TAB_PRECO  
	INNER JOIN PRODUTOS B (NOLOCK) ON A.PRODUTO = B.PRODUTO 
	INNER JOIN WS_PRODUTOS_INTERNET WS ON B.PRODUTO = WS.PRODUTO

	/*--  EXEC ('
	--  IF OBJECT_ID(''SOMA_LINX.DBO.WS_PRODUTOS_PRECOS_JsonTmp'') IS NOT NULL 
	--	DROP TABLE SOMA_LINX.DBO.WS_PRODUTOS_PRECOS_JsonTmp; 
	--  CREATE TABLE SOMA_LINX.DBO.WS_PRODUTOS_PRECOS_JsonTmp (Col1 VARCHAR(MAX));
	--  ') 
	--  AT WISE_AZURE;

	--  SET @TSQL = '
	--  DECLARE @json VARCHAR(MAX)
	--  SET @json = (SELECT A.CODIGO_TAB_PRECO, A.PRODUTO, A.PRECO1,A.PROMOCAO_DESCONTO,WS.ID_CAMPANHA  
	--				  FROM PRODUTOS_PRECOS A WITH (NOLOCK)   
	--						  INNER JOIN (SELECT CODIGO_TAB_PRECO FROM TABELAS_PRECO (NOLOCK) WHERE TABELA LIKE ''%ATACADO%'' OR CODIGO_TAB_PRECO=''VO'') TAB ON TAB.CODIGO_TAB_PRECO = A.CODIGO_TAB_PRECO  
	--						  INNER JOIN PRODUTOS B (NOLOCK) ON A.PRODUTO = B.PRODUTO 
	--						  INNER JOIN WS_PRODUTOS_INTERNET WS ON B.PRODUTO = WS.PRODUTO
	--				  FOR JSON PATH);

	--  INSERT INTO [WISE_AZURE].SOMA_LINX.DBO.WS_PRODUTOS_PRECOS_JsonTmp(Col1)
	--  VALUES (@json);
	--  '
	--  EXEC (@TSQL)

	--  SET @TSQL = '
	--  DECLARE @json VARCHAR(MAX)
	--  SET @json = (SELECT Col1 FROM SOMA_LINX.DBO.WS_PRODUTOS_PRECOS_JsonTmp)

	--  INSERT INTO [Soma_Linx].[dbo].WS_PRODUTOS_PRECOS (CODIGO_TAB_PRECO,  PRODUTO, PRECO1, PROMOCAO_DESCONTO, ID_CAMPANHA) 
	--  SELECT CODIGO_TAB_PRECO, PRODUTO, PRECO1, PROMOCAO_DESCONTO, ID_CAMPANHA
	--  FROM OPENJSON(@json) 
	--  WITH (
	--	CODIGO_TAB_PRECO CHAR(2),
	--	PRODUTO CHAR(12), 
	--	PRECO1 [numeric](14, 2), 
	--	PROMOCAO_DESCONTO [numeric](8, 5), 
	--	ID_CAMPANHA INT
	--	)
	--  '
	--EXEC (@TSQL) AT [WISE_AZURE] */
	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA
END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

-- Cadastro de IPI
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_CLASSIF_FISCAL','WS_CLASSIF_FISCAL_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_CLASSIF_FISCAL')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_CLASSIF_FISCAL]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]') AT WISE_AZURE 
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	--#GS:02.10#
	SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
	EXEC (@TSQL)

	SET @CAMPANHA = (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]
	SELECT 
		A.CLASSIF_FISCAL, A.IPI, @CAMPANHA AS ID_CAMPANHA
	FROM 
		CLASSIF_FISCAL (NOLOCK) A
	WHERE 
		A.IPI > 0
	
	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

--#GS:01.03# - PROP_PRODUTO
BEGIN TRY 
 	INSERT INTO #TABELAS 
	SELECT 'WS_PROP_PRODUTOS','WS_PROP_PRODUTOS_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL
	
	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_PROP_PRODUTOS')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_PROP_PRODUTOS]')	AT WISE_AZURE

	EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_PROP_PRODUTOS]') AT WISE_AZURE 

	INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_PROP_PRODUTOS 
	SELECT B.ID_CAMPANHA, A.PROPRIEDADE, A.PRODUTO, ITEM_PROPRIEDADE, VALOR_PROPRIEDADE, DATA_PARA_TRANSFERENCIA, GETDATE() AS DT_INTEGRACAO, NULL AS DT_EXCLUSAO 
	FROM 
	PROP_PRODUTOS (NOLOCK) A
	INNER JOIN WS_PRODUTOS_INTERNET (NOLOCK) B ON A.PRODUTO=B.PRODUTO
	WHERE A.PROPRIEDADE='00717'
 	
	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

-- MARCO OS PRODUTOS QUE FORAM EXCLUIDOS DT_EXCLUSAO
UPDATE A SET DT_EXCLUSAO=CONVERT(VARCHAR(10),GETDATE(),112)
FROM
 [WISE_AZURE].[SOMA_LINX].[DBO].WS_PRODUTOS A

LEFT JOIN WS_PRODUTOS_INTERNET WS  ON A.PRODUTO = WS.PRODUTO
WHERE
WS.PRODUTO IS NULL AND A.DT_EXCLUSAO IS NULL and WS.ID_CAMPANHA <> '99'

--AJUSTAS AS CORES NÃO LIBERADAS

UPDATE A SET DT_EXCLUSAO=CONVERT(VARCHAR(10),GETDATE(),112)
FROM
 [WISE_AZURE].[SOMA_LINX].[DBO].WS_PRODUTO_CORES A
LEFT JOIN WS_PRODUTOS_INTERNET WS  ON A.PRODUTO = WS.PRODUTO
WHERE
WS.PRODUTO IS NULL AND A.DT_EXCLUSAO IS NULL and WS.ID_CAMPANHA <> '99' -- '99' é a Campanha do Me Leva Pronta Entrega

UPDATE A
SET A.DT_EXCLUSAO=GETDATE()
FROM
[WISE_AZURE].[Soma_Linx].[dbo].WS_PRODUTO_CORES A
INNER JOIN PRODUTO_CORES (NOLOCK) B ON A.PRODUTO=B.PRODUTO AND A.COR_PRODUTO=B.COR_PRODUTO
WHERE B.STATUS_VENDA_ATUAL <> 1

-- LIMPA AS TABELAS QUE TIVERAO SUCESSO NA INTEGRAÇÃO
SET @TABELA=''

DECLARE XCURSOR CURSOR FOR

	SELECT RTRIM(LTRIM(TABELA_BKP)) AS TABELA_DELETAR FROM #TABELAS WHERE PROCESSADO = 1

OPEN XCURSOR
FETCH NEXT FROM XCURSOR INTO @TABELA

WHILE @@FETCH_STATUS = 0
BEGIN
	EXEC ('DROP TABLE [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE
	FETCH NEXT FROM XCURSOR INTO @TABELA
END

CLOSE XCURSOR
DEALLOCATE XCURSOR


DECLARE XCURSOR CURSOR FOR

	SELECT RTRIM(LTRIM(TABELA_BKP)) AS TABELA_DELETAR, TABELA FROM #TABELAS WHERE PROCESSADO = 0

OPEN XCURSOR
FETCH NEXT FROM XCURSOR INTO @TABELA, @TABELA_OLD

WHILE @@FETCH_STATUS = 0
BEGIN
	--- LIMPO A TABELA ORIGINAL
	EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].['+@TABELA_OLD+']')	AT WISE_AZURE
	--- VOLTO O BACKUP
	EXEC ('INSERT INTO [Soma_Linx].[dbo].['+@TABELA_OLD+'] SELECT * FROM [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE
	--- APAGO A TABELA TEMPORARIA
	EXEC ('DROP TABLE [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE

	FETCH NEXT FROM XCURSOR INTO @TABELA, @TABELA_OLD
END

CLOSE XCURSOR
DEALLOCATE XCURSOR

DROP TABLE #TABELAS