
CREATE PROCEDURE [dbo].[PROC_INTEGRACAO_LINX_WISE_TB_AUXILIARES_COM_ESTOQUE] (@TIPO INT = 0)
AS

 -- #GS:05.04# - Silvio Luiz - 09/10/2025 - Subir toda a PRODUTOS_PERIODOS_ENTREGAS para WS_GS_PERIODO_PCP - Solicitação Farm ETC
 -- #GS:05.03# - Silvio Luiz - 13/07/2023 - Voltar com o bloco de formas pgto no @tipo = 1 e incluir o w_colecoes para todas os id_campanha
 -- #GS:05.02# - Guilherme Rocha - 05/05/2023 - Adicionado fechamento e desalocacao do cursor
 -- #GS:05.01# - Marco Banaggia  - 28/04/2023 - Ajuste para levar as campnahs ativas, pois estava indo null na variavel @campanha devido a mais de uma campanha ativa
 -- #GS:04.01# - Marco Banaggia  - 15/07/2021 - Retorno da proc anterior.
 -- #GS:03.01# - Marco Banaggia  - 31/03/2020 - Inclusão da tabela COLECOES, conforme solicitação via e-mail.
 -- #GS:02.01# - Silvio Luiz     - 29/04/2020 - Tratamento para deletar somente o id_campanha ativo do Grupo Soma
 -- #GS:01.03# - Marco Banaggia  - 31/07/2019 - Inclusão dos produtos Pranta Entrega do Me Leva.
 -- #GS:01.01# - Marco Banaggia  - 22/07/2019 - Inclusão para levar as classificações Fiscais que contem IPI.

DECLARE @CAMPANHA VARCHAR(500), @TSQL VARCHAR(MAX) 

SET @TSQL = ''
DECLARE @StrAgg_ID_CAMPANHA VARCHAR(MAX) = ''
SELECT @StrAgg_ID_CAMPANHA = ISNULL(STUFF(
                                            (SELECT ',' + CONVERT(VARCHAR(MAX), t.ID_CAMPANHA)
                                               FROM (SELECT DISTINCT ISNULL(ID_CAMPANHA, '') AS ID_CAMPANHA
                                                       FROM WS_PRODUTOS_INTERNET) AS t
                                                FOR XML PATH('')
                                            ), 
                                          1, LEN(','), ''), '0')

DECLARE @StrAgg_REDE_LOJAS VARCHAR(MAX) = ''
SELECT @StrAgg_REDE_LOJAS = ISNULL(STUFF(
                                            (SELECT ',' + CONVERT(VARCHAR(MAX), t.REDE_LOJAS)
                                               FROM (SELECT DISTINCT ISNULL(REDE_LOJAS, '') AS REDE_LOJAS
                                                       FROM WS_PRODUTOS_INTERNET) AS t
                                                FOR XML PATH('')
                                            ), 
                                          1, LEN(','), ''), '0')


IF @TIPO = 0
BEGIN
	EXEC PROC_SELECIONA_PRODUTOS_LINX_WISE
	
	-- LIMPA AS TABELAS NO WISE_AZURE ANTES DA CARGA
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_TABELAS_PRECO]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_FORMA_PGTO]')		AT WISE_AZURE

-- #GS:04.01# - INICIO

	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB] WHERE MARCA IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB] WHERE MARCA IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB] WHERE REDE_LOJAS IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB] WHERE REDE_LOJAS IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	--DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) OR ID_CAMPANHA IS NULL
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_FORMA_PGTO] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) /* ADCIONADO EM 31/03/2021 - sOLICITAÇÃO VIA E-MAIL DA COMPUTWISE */


 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB] WHERE MARCA IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB] WHERE MARCA IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB] WHERE REDE_LOJAS IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB] WHERE REDE_LOJAS IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ') OR ID_CAMPANHA IS NULL'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_FORMA_PGTO] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES]'
 --EXEC (@TSQL)

 -- #GS:04.01# - FIM

	-- ALIMENTA AS TABELAS NO WISE_AZURE
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB]
	SELECT marca, clifor_cliente, valor_meta, DATA_INCLUSAO, DATA_ALTERACAO, GETDATE() 
	FROM GS_TB_META_REPRE_WEB where marca in (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB]
	SELECT *,GETDATE(),NULL FROM GS_TB_LIMITE_VALOR_WEB

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_COLECOES_FRETE_LINXWEB
	SELECT COLECAO_1,COLECAO_2,REDE_LOJAS,GETDATE(),NULL FROM GS_COLECOES_FRETE_LINXWEB

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_CIF_LINXWEB
	SELECT *,GETDATE(),NULL FROM GS_CONDICOES_CIF_LINXWEB


	--#GS:01# - Marco Banaggia - Colocando ID_Colecao a pedido do Wise
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_PGTO_LINXWEB
	SELECT DISTINCT A.*,GETDATE(),NULL, B.ID_CAMPANHA 
	FROM 
	GS_CONDICOES_PGTO_LINXWEB A
	inner join (
	SELECT DISTINCT B.REDE_LOJAS,B.COLECAO,B.ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK)  A
									JOIN GS_CAMPANHA_ATACADO_COLECOES (NOLOCK)  B ON A.ID_CAMPANHA = B.ID_CAMPANHA
								WHERE A.COLECAO_ATIVA = 1 

		   union
		   SELECT '29','VER20', '99'
		   union
		   SELECT '29','AI20', '99'
	) B ON A.REDE_LOJAS=B.REDE_LOJAS AND (A.COLECAO_1=B.COLECAO or a.COLECAO_2=B.COLECAO)


	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_DATA_ENTREGA_PEDIDOS_ATAC
	SELECT A.*,GETDATE(),NULL, B.ID_CAMPANHA 
	FROM 
	GS_DATA_ENTREGA_PEDIDOS_ATAC A
	inner join (
	SELECT DISTINCT B.REDE_LOJAS,B.COLECAO,B.ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK)  A
									JOIN GS_CAMPANHA_ATACADO_COLECOES (NOLOCK)  B ON A.ID_CAMPANHA = B.ID_CAMPANHA
								WHERE A.COLECAO_ATIVA = 1 
	) B ON A.REDE_LOJAS=B.REDE_LOJAS AND A.COLECAO=B.COLECAO

	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_PGTO_LINXWEB
	--SELECT *,GETDATE(),NULL FROM GS_CONDICOES_PGTO_LINXWEB

	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_DATA_ENTREGA_PEDIDOS_ATAC
	--SELECT *,GETDATE(),NULL FROM GS_DATA_ENTREGA_PEDIDOS_ATAC

	--SALDO DISPONIVEL
	--DELETE GS_LOG_SALDO_WEB_WISE WHERE CAST(DATA_SALDO AS DATE) = CAST(GETDATE() AS DATE)

	--INSERT INTO GS_LOG_SALDO_WEB_WISE
	--SELECT 
	--	ID_CAMPANHA,LIBERAR_GRADE_WEB,PRODUTO,COR_PRODUTO,
	--	SALDO_DISPONIVEL,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D12,D11,D13,D14,D15,D16,
	--	TOT_COMPRAS,CO1,CO2,CO3,CO4,CO5,CO6,CO7,CO8,CO9,CO10,CO11,CO12,CO13,CO14,CO15,CO16,
	--	QTDE_PROGRAMADA_ATACADO,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,
	--	TOT_PRODEXTRA,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX10,EX11,EX12,EX13,EX14,EX15,EX16,
	--	TOT_PRODUCAO_S_PRODUCAO,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,PO16,
	--	QTDE_VENDIDA,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,
	--	TOT_VENDAS_LOTE,VO1,VO2,VO3,VO4,VO5,VO6,VO7,VO8,VO9,VO10,VO11,VO12,VO13,VO14,VO15,VO16,
	--	TOT_VENDAS_LOTE_ABERTAS,VOA1,VOA2,VOA3,VOA4,VOA5,VOA6,VOA7,VOA8,VOA9,VOA10,VOA11,VOA12,VOA13,VOA14,VOA15,VOA16
	--	,GETDATE() AS DATA_SALDO,LIBERAR_GRADE_WEB_REAL 
	--FROM FN_CONSULTA_SALDO_WEB_WISE('%','%',NULL,NULL)
	
	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_ESTOQUE_PRODUTOS(LIBERAR_GRADE_WEB, PRODUTO, COR_PRODUTO, ESTOQUE, ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, DATA_PARA_TRANSFERENCIA,ID_CAMPANHA )
	--SELECT LIBERAR_GRADE_WEB, PRODUTO, COR_PRODUTO, SALDO_DISPONIVEL, D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, GETDATE() AS DATA_PARA_TRANSFERENCIA,ID_CAMPANHA FROM FN_CONSULTA_SALDO_WEB_WISE('%','%',NULL,NULL)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_TABELAS_PRECO
	SELECT CODIGO_TAB_PRECO, REPLACE(TABELA,'VENDA ATACADO','ATAC') AS TABELA,GETDATE(),NULL 
		FROM TABELAS_PRECO (NOLOCK) WHERE TABELA LIKE '%ATACADO%' AND CODIGO_TAB_PRECO NOT IN (SELECT CODIGO_TAB_PRECO FROM [WISE_AZURE].[SOMA_LINX].[DBO].WS_TABELAS_PRECO)

	--#GS:01.03#  --- INICIO ----
	Exec PROC_INTEGRACAO_LINX_WISE_PRODUTOS_PE

	--#GS:01.03# --- FINAL -----

	-- #GS:05.01# -- INICIAL ----
	DECLARE XCURSOR CURSOR FOR
		SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET
	OPEN XCURSOR
	FETCH NEXT FROM XCURSOR INTO @CAMPANHA
	WHILE @@FETCH_STATUS=0
	BEGIN
	--#GS:01.02#
	--SET @CAMPANHA = (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) -- #GS:05.01#
		INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]
		SELECT 
			A.CLASSIF_FISCAL, A.IPI,
			@CAMPANHA AS ID_CAMPANHA
		FROM 
			CLASSIF_FISCAL (NOLOCK) A
		WHERE A.IPI > 0

		INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP]
		SELECT DISTINCT
		A.PERIODO_PCP, A.ENTREGA, A.LIMITE, GETDATE() AS DT_INTEGRACAO, @CAMPANHA AS ID_CAMPANHA
		FROM PRODUTOS_PERIODOS_ENTREGAS (NOLOCK) A
		--INNER JOIN PRODUTOS (NOLOCK) B ON A.PERIODO_PCP=B.PERIODO_PCP AND B.FABRICANTE=B.PERIODO_PCP AND B.REDE_LOJAS='29'

		FETCH NEXT FROM XCURSOR INTO @CAMPANHA
	END
	-- #GS:05.02# -- INICIO
	CLOSE XCURSOR
	DEALLOCATE XCURSOR
	-- #GS:05.02# -- FIM
	-- #GS:05.01# - FINAL ----

	-- FORMAS DE PGTO
	INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_FORMA_PGTO (
		CONDICAO_PGTO
		,DESC_COND_PGTO
		,ID_CAMPANHA,
		TIPO_CONDICAO,
		NUMERO_PARCELAS,
		DESCONTO
		)
	SELECT A.CONDICAO_PGTO
		,A.DESC_COND_PGTO
		,B.ID_CAMPANHA,
		TIPO_CONDICAO,
		NUMERO_PARCELAS,
		DESCONTO
	FROM FORMA_PGTO A WITH (NOLOCK)
		JOIN GS_CAMPANHA_ATACADO (NOLOCK) B ON COLECAO_ATIVA = 1
	-- FORMAS DE PGTO CLIENTES
	--INSERT INTO WS_FORMA_PGTO_CLIENTES (CONDICAO_PGTO, CLIENTE_ATACADO, CLIFOR, DATA_PARA_TRANSFERENCIA)
	--	SELECT DISTINCT LTRIM(RTRIM(A.VALOR_PROPRIEDADE)) AS CONDICAO_PGTO, A.CLIENTE_ATACADO, B.CLIFOR, A.DATA_PARA_TRANSFERENCIA
	--		FROM PROP_CLIENTES_ATACADO A WITH (NOLOCK)  
	--		INNER JOIN WS_CLIENTES_ATACADO B WITH (NOLOCK)  
	--			ON B.CLIENTE_ATACADO = A.CLIENTE_ATACADO

	-- COLEÇÕES
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES]
	SELECT (SELECT TOP 1 ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK) WHERE COLECAO_ATIVA = 1) AS ID_CAMPANHA, COLECAO, DESC_COLECAO FROM COLECOES (NOLOCK)

END
ELSE
BEGIN
	-- LIMPA AS TABELAS NO WISE_AZURE ANTES DA CARGA
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_TABELAS_PRECO]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP]') AT WISE_AZURE
	--EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].[WS_FORMA_PGTO]')		AT WISE_AZURE

-- #GS:04.01# - INICIO
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB] WHERE MARCA IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB] WHERE MARCA IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB] WHERE REDE_LOJAS IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB] WHERE REDE_LOJAS IN (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) OR ID_CAMPANHA IS NULL
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_FORMA_PGTO] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) /* ADCIONADO EM 31/03/2021 - sOLICITAÇÃO VIA E-MAIL DA COMPUTWISE */
	

 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB] WHERE MARCA IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB] WHERE MARCA IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_COLECOES_FRETE_LINXWEB] WHERE REDE_LOJAS IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_CIF_LINXWEB] WHERE REDE_LOJAS IN (' +  @StrAgg_REDE_LOJAS + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_CONDICOES_PGTO_LINXWEB] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_DATA_ENTREGA_PEDIDOS_ATAC] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ') OR ID_CAMPANHA IS NULL'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_FORMA_PGTO] WHERE ID_CAMPANHA IN (' +  @StrAgg_ID_CAMPANHA + ')'
 --EXEC (@TSQL)
 --SET @TSQL = 'DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES]'
 --EXEC (@TSQL)

 -- #GS:04.01# - FIM

	-- ALIMENTA AS TABELAS NO WISE_AZURE
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_META_REPRE_WEB]
	SELECT marca, clifor_cliente, valor_meta, DATA_INCLUSAO, DATA_ALTERACAO, GETDATE() 
	FROM GS_TB_META_REPRE_WEB where marca in (SELECT DISTINCT REDE_LOJAS FROM WS_PRODUTOS_INTERNET)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_TB_LIMITE_VALOR_WEB]
	SELECT *,GETDATE(),NULL FROM GS_TB_LIMITE_VALOR_WEB

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_COLECOES_FRETE_LINXWEB
	SELECT COLECAO_1,COLECAO_2,REDE_LOJAS,GETDATE(),NULL FROM GS_COLECOES_FRETE_LINXWEB

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_CIF_LINXWEB
	SELECT *,GETDATE(),NULL FROM GS_CONDICOES_CIF_LINXWEB


	--#GS:01# - Marco Banaggia - Colocando ID_Colecao a pedido do Wise
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_PGTO_LINXWEB
	SELECT A.*,GETDATE(),NULL, B.ID_CAMPANHA 
	FROM 
	GS_CONDICOES_PGTO_LINXWEB A
	inner join (
	SELECT DISTINCT B.REDE_LOJAS,B.COLECAO,B.ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK)  A
									JOIN GS_CAMPANHA_ATACADO_COLECOES (NOLOCK)  B ON A.ID_CAMPANHA = B.ID_CAMPANHA
								WHERE A.COLECAO_ATIVA = 1 
	) B ON A.REDE_LOJAS=B.REDE_LOJAS AND (A.COLECAO_1=B.COLECAO or a.COLECAO_2=B.COLECAO)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_DATA_ENTREGA_PEDIDOS_ATAC
	SELECT A.*,GETDATE(),NULL, B.ID_CAMPANHA 
	FROM 
	GS_DATA_ENTREGA_PEDIDOS_ATAC A
	inner join (
	SELECT DISTINCT B.REDE_LOJAS,B.COLECAO,B.ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK)  A
									JOIN GS_CAMPANHA_ATACADO_COLECOES (NOLOCK)  B ON A.ID_CAMPANHA = B.ID_CAMPANHA
								WHERE A.COLECAO_ATIVA = 1 
	) B ON A.REDE_LOJAS=B.REDE_LOJAS AND A.COLECAO=B.COLECAO

	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_CONDICOES_PGTO_LINXWEB
	--SELECT *,GETDATE(),NULL FROM GS_CONDICOES_PGTO_LINXWEB

	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_GS_DATA_ENTREGA_PEDIDOS_ATAC
	--SELECT *,GETDATE(),NULL FROM GS_DATA_ENTREGA_PEDIDOS_ATAC

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_TABELAS_PRECO
	SELECT CODIGO_TAB_PRECO, REPLACE(TABELA,'VENDA ATACADO','ATAC') AS TABELA,GETDATE(),NULL 
		FROM TABELAS_PRECO (NOLOCK) WHERE TABELA LIKE '%ATACADO%' AND CODIGO_TAB_PRECO NOT IN (SELECT CODIGO_TAB_PRECO FROM [WISE_AZURE].[SOMA_LINX].[DBO].WS_TABELAS_PRECO)

	-- #GS01.02#
	--SET @CAMPANHA = (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]
	--SELECT 
	--	A.CLASSIF_FISCAL, A.IPI,
	--	@CAMPANHA AS ID_CAMPANHA
	--FROM 
	--	CLASSIF_FISCAL (NOLOCK) A
	--WHERE A.IPI > 0


  EXEC ('
  IF OBJECT_ID(''SOMA_LINX.DBO.WS_CLASSIF_FISCAL_JsonTmp'') IS NOT NULL 
    DROP TABLE SOMA_LINX.DBO.WS_CLASSIF_FISCAL_JsonTmp; 
  CREATE TABLE SOMA_LINX.DBO.WS_CLASSIF_FISCAL_JsonTmp (Col1 VARCHAR(MAX));
  ') 
  AT WISE_AZURE;

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT 
		               A.CLASSIF_FISCAL, A.IPI,
		               (SELECT DISTINCT TOP 1 ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) AS ID_CAMPANHA
	               FROM 
		               CLASSIF_FISCAL (NOLOCK) A
	               WHERE A.IPI > 0
                  FOR JSON PATH);

  INSERT INTO [WISE_AZURE].SOMA_LINX.DBO.WS_CLASSIF_FISCAL_JsonTmp(Col1)
  VALUES (@json);
  '
  EXEC (@TSQL)

  SET @TSQL = '
  DECLARE @json VARCHAR(MAX)
  SET @json = (SELECT Col1 FROM SOMA_LINX.DBO.WS_CLASSIF_FISCAL_JsonTmp)

  INSERT INTO [SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]
  SELECT CLASSIF_FISCAL, IPI, ID_CAMPANHA
  FROM OPENJSON(@json) 
  WITH (
    CLASSIF_FISCAL CHAR(10), 
    IPI [numeric](8, 5), 
    ID_CAMPANHA INT
    )
  '
  EXEC (@TSQL) AT [WISE_AZURE]

	-- #GS:05.01# - INICIO ----
	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP]
	--SELECT DISTINCT
	--A.PERIODO_PCP, A.ENTREGA, A.LIMITE, GETDATE() AS DT_INTEGRACAO--, @CAMPANHA AS ID_CAMPANHA
	--FROM PRODUTOS_PERIODOS_ENTREGAS (NOLOCK) A
	--INNER JOIN PRODUTOS (NOLOCK) B ON A.PERIODO_PCP=B.PERIODO_PCP AND B.FABRICANTE=B.PERIODO_PCP AND B.REDE_LOJAS='29'

	---- FORMAS DE PGTO
	INSERT INTO [WISE_AZURE].[Soma_Linx].[dbo].WS_FORMA_PGTO (
		CONDICAO_PGTO
		,DESC_COND_PGTO
		,ID_CAMPANHA,
		TIPO_CONDICAO,
		NUMERO_PARCELAS,
		DESCONTO
		)
	SELECT A.CONDICAO_PGTO
		,A.DESC_COND_PGTO
		,B.ID_CAMPANHA,
		TIPO_CONDICAO,
		NUMERO_PARCELAS,
		DESCONTO
	FROM FORMA_PGTO A WITH (NOLOCK)
		JOIN GS_CAMPANHA_ATACADO (NOLOCK) B ON COLECAO_ATIVA = 1
	-- #GS:05.01# - FINAL ----

	-- FORMAS DE PGTO CLIENTES
	--INSERT INTO WS_FORMA_PGTO_CLIENTES (CONDICAO_PGTO, CLIENTE_ATACADO, CLIFOR, DATA_PARA_TRANSFERENCIA)
	--	SELECT DISTINCT LTRIM(RTRIM(A.VALOR_PROPRIEDADE)) AS CONDICAO_PGTO, A.CLIENTE_ATACADO, B.CLIFOR, A.DATA_PARA_TRANSFERENCIA
	--		FROM PROP_CLIENTES_ATACADO A WITH (NOLOCK)  
	--		INNER JOIN WS_CLIENTES_ATACADO B WITH (NOLOCK)  
	--			ON B.CLIENTE_ATACADO = A.CLIENTE_ATACADO

	-- #GS:05.01# -- INICIAL ----
	DECLARE XCURSOR CURSOR FOR
		SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET
	OPEN XCURSOR
	FETCH NEXT FROM XCURSOR INTO @CAMPANHA
	WHILE @@FETCH_STATUS=0
	BEGIN
	--#GS:01.02#
	--SET @CAMPANHA = (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET) -- #GS:05.01#
		INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_CLASSIF_FISCAL]
		SELECT 
			A.CLASSIF_FISCAL, A.IPI,
			@CAMPANHA AS ID_CAMPANHA
		FROM 
			CLASSIF_FISCAL (NOLOCK) A
		WHERE A.IPI > 0

		INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_GS_PERIODO_PCP]
		SELECT DISTINCT
		A.PERIODO_PCP, A.ENTREGA, A.LIMITE, GETDATE() AS DT_INTEGRACAO, @CAMPANHA AS ID_CAMPANHA
		FROM PRODUTOS_PERIODOS_ENTREGAS (NOLOCK) A
		--INNER JOIN PRODUTOS (NOLOCK) B ON A.PERIODO_PCP=B.PERIODO_PCP AND B.FABRICANTE=B.PERIODO_PCP AND B.REDE_LOJAS='29'

		INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES]
		SELECT @CAMPANHA AS ID_CAMPANHA, COLECAO, DESC_COLECAO FROM COLECOES (NOLOCK)


		FETCH NEXT FROM XCURSOR INTO @CAMPANHA
	END
	-- #GS:05.02# --INICIO
	CLOSE XCURSOR
	DEALLOCATE XCURSOR
	-- #GS:05.02# - FIM
	-- #GS:05.01# - FINAL ----
	-- COLEÇÕES
	--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_COLECOES]
	--SELECT (SELECT TOP 1 ID_CAMPANHA FROM GS_CAMPANHA_ATACADO (NOLOCK) WHERE COLECAO_ATIVA = 1) AS ID_CAMPANHA, COLECAO, DESC_COLECAO FROM COLECOES (NOLOCK)


END

