
CREATE PROCEDURE [dbo].[PROC_INTEGRACAO_LINX_WISE_ESTOQUE]   
AS  

-- #GRUPOSOMA:05# - 04/06/2024 - Silvio Luiz - Tabela de consulta de saldo no DB_Views para o Atacado
-- #GRUPOSOMA:04# - 28/11/2023 - Guilherme Rocha - Ajustado o delete e adicionado o FAST_FORWARD nos cursores.
-- 11/05/2021 - Guilherme Rocha - Rollback na procedure.
-- #GS:02.01# - Silvio Luiz - 29/04/2020 - Tratamento para deletar somente o id_campanha ativo do Grupo Soma 
-- #GRUPOSOMA:03# -	22/08/2019 - Marco Banaggia	- Ajuste para o estoque do Printa Entrega
-- #GRUPOSOMA:02# -	18/04/2019 - Marco Banaggia	- Alteração para envio full do Estoque
-- #GRUPOSOMA:01# -	10/04/2019 - Marco Banaggia	- Correção do campo de posicao 15, estava colocando a posicao 1

DECLARE @DT_SALDO DATE, @TABELA varchar(500), @TABELA_OLD VARCHAR(500)

CREATE TABLE #TABELAS (TABELA VARCHAR(100), TABELA_BKP VARCHAR(100),PROCESSADO BIT, ERROR VARCHAR(MAX))

SET @DT_SALDO= CAST(GETDATE() AS DATE)

EXEC PROC_SELECIONA_PRODUTOS_LINX_WISE
  
--DELETE GS_LOG_SALDO_WEB_WISE WHERE CAST(DATA_SALDO AS DATE) = CAST(GETDATE() AS DATE)  
--DELETE GS_LOG_SALDO_WEB_WISE WHERE CAST(DATA_SALDO AS DATE) = @DT_SALDO -- #GRUPOSOMA:02#
DELETE GS_LOG_SALDO_WEB_WISE WHERE DATA_SALDO = @DT_SALDO -- #GRUPOSOMA:02#  -- #GRUPOSOMA:04#

DELETE DB_VIEWS.DBO.GS_LOG_SALDO_ATACADO_WISE WHERE DATA_SALDO = @DT_SALDO -- #GRUPOSOMA:05# 
  
INSERT INTO GS_LOG_SALDO_WEB_WISE WITH (TABLOCK) 
--SELECT *,CAST(GETDATE() AS DATE) AS DATA_SALDO FROM FN_CONSULTA_SALDO_WEB_WISE('%','%',NULL,NULL)  
-- #GRUPOSOMA:02#
SELECT
	A.ID_CAMPANHA
	,LIBERAR_GRADE_WEB,A.PRODUTO,COR_PRODUTO,
	SALDO_DISPONIVEL,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D12,D11,D13,D14,D15,D16,
	TOT_COMPRAS,CO1,CO2,CO3,CO4,CO5,CO6,CO7,CO8,CO9,CO10,CO11,CO12,CO13,CO14,CO15,CO16,
	QTDE_PROGRAMADA_ATACADO,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,
	TOT_PRODEXTRA,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX10,EX11,EX12,EX13,EX14,EX15,EX16,
	TOT_PRODUCAO_S_PRODUCAO,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,PO16,
	QTDE_VENDIDA,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,
	TOT_VENDAS_LOTE,VO1,VO2,VO3,VO4,VO5,VO6,VO7,VO8,VO9,VO10,VO11,VO12,VO13,VO14,VO15,VO16,
	TOT_VENDAS_LOTE_ABERTAS,VOA1,VOA2,VOA3,VOA4,VOA5,VOA6,VOA7,VOA8,VOA9,VOA10,VOA11,VOA12,VOA13,VOA14,VOA15,VOA16
	,@DT_SALDO AS DATA_SALDO,LIBERAR_GRADE_WEB_REAL  
FROM 
	FN_CONSULTA_SALDO_WEB_WISE('%','%',NULL,NULL)  A
	INNER JOIN WS_PRODUTOS_INTERNET B ON A.PRODUTO=B.PRODUTO AND A.ID_CAMPANHA=B.ID_CAMPANHA
WHERE B.ENVIA_ATACADO_INTERNET = 1

INSERT INTO DB_VIEWS.DBO.GS_LOG_SALDO_ATACADO_WISE WITH (TABLOCK) 
-- #GRUPOSOMA:05#
SELECT
	ID_CAMPANHA
	,LIBERAR_GRADE_WEB,PRODUTO,COR_PRODUTO,
	SALDO_DISPONIVEL,D1,D2,D3,D4,D5,D6,D7,D8,D9,D10,D12,D11,D13,D14,D15,D16,
	TOT_COMPRAS,CO1,CO2,CO3,CO4,CO5,CO6,CO7,CO8,CO9,CO10,CO11,CO12,CO13,CO14,CO15,CO16,
	QTDE_PROGRAMADA_ATACADO,P1,P2,P3,P4,P5,P6,P7,P8,P9,P10,P11,P12,P13,P14,P15,P16,
	TOT_PRODEXTRA,EX1,EX2,EX3,EX4,EX5,EX6,EX7,EX8,EX9,EX10,EX11,EX12,EX13,EX14,EX15,EX16,
	TOT_PRODUCAO_S_PRODUCAO,PO1,PO2,PO3,PO4,PO5,PO6,PO7,PO8,PO9,PO10,PO11,PO12,PO13,PO14,PO15,PO16,
	QTDE_VENDIDA,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,V11,V12,V13,V14,V15,V16,
	TOT_VENDAS_LOTE,VO1,VO2,VO3,VO4,VO5,VO6,VO7,VO8,VO9,VO10,VO11,VO12,VO13,VO14,VO15,VO16,
	TOT_VENDAS_LOTE_ABERTAS,VOA1,VOA2,VOA3,VOA4,VOA5,VOA6,VOA7,VOA8,VOA9,VOA10,VOA11,VOA12,VOA13,VOA14,VOA15,VOA16
	,@DT_SALDO AS DATA_SALDO
	,LIBERAR_GRADE_WEB_REAL  
FROM 
	GS_LOG_SALDO_WEB_WISE
WHERE 
	DATA_SALDO=@DT_SALDO
	

--#GRUPOSOMA:02# INICIO
--UPDATE A SET 
--	A.DT_EXCLUSAO     = CASE WHEN B.PRODUTO IS NULL THEN CONVERT(VARCHAR(10),GETDATE(),112) ELSE NULL END,
--	A.DT_INTEGRACAO   = CAST(GETDATE() AS SMALLDATETIME)
--FROM [WISE_AZURE].[SOMA_LINX].[DBO].WS_ESTOQUE_PRODUTOS_PWT A  
-- LEFT JOIN GS_LOG_SALDO_WEB_WISE (NOLOCK) B 
-- ON A.PRODUTO = B.PRODUTO AND A.COR_PRODUTO = B.COR_PRODUTO AND B.DATA_SALDO = CAST(GETDATE() AS DATE)  AND A.ID_CAMPANHA = A.ID_CAMPANHA
--WHERE  ISNULL(CONVERT(VARCHAR(10),A.DT_EXCLUSAO,112),'') <> CASE WHEN B.PRODUTO IS NULL THEN CONVERT(VARCHAR(10),GETDATE(),112)  ELSE '' END

--UPDATE A SET  
-- ID_CAMPANHA = B.ID_CAMPANHA,
-- LIBERAR_GRADE_WEB = B.LIBERAR_GRADE_WEB,
-- ESTOQUE=B.SALDO_DISPONIVEL,   
-- ES1 =B.D1 , ES2 =B.D2 , ES3 =B.D3 , ES4 =B.D4 , ES5=B.D5  , ES6 =B.D6 ,ES7 =B.D7, ES8=B.D8,    
---- ES9 =B.D9 , ES10=B.D10, ES11=B.D11, ES12=B.D12, ES13=B.D13, ES14=B.D14,ES15=B.D1, ES16=B.D16, --#GRUPOSOMA:01#
-- ES9 =B.D9 , ES10=B.D10, ES11=B.D11, ES12=B.D12, ES13=B.D13, ES14=B.D14,ES15=B.D15, ES16=B.D16,  
-- DT_INTEGRACAO = CAST(GETDATE() AS SMALLDATETIME),  
-- DT_EXCLUSAO   = NULL  
--FROM [WISE_AZURE].[SOMA_LINX].[DBO].WS_ESTOQUE_PRODUTOS_PWT A  
-- JOIN GS_LOG_SALDO_WEB_WISE (NOLOCK) B ON A.PRODUTO = B.PRODUTO AND A.COR_PRODUTO = B.COR_PRODUTO  AND B.DATA_SALDO = CAST(GETDATE() AS DATE) AND A.ID_CAMPANHA = A.ID_CAMPANHA
--WHERE A.DT_EXCLUSAO IS NULL AND
--	  CHECKSUM(A.ID_CAMPANHA,A.LIBERAR_GRADE_WEB, A.PRODUTO, A.COR_PRODUTO, A.ESTOQUE, A.ES1, A.ES2, A.ES3, A.ES4, A.ES5, A.ES6, A.ES7, A.ES8, A.ES9, A.ES10, A.ES11, A.ES12, A.ES13, A.ES14, A.ES15, A.ES16 ) <>   
--      CHECKSUM(B.ID_CAMPANHA,B.LIBERAR_GRADE_WEB, B.PRODUTO, B.COR_PRODUTO, B.SALDO_DISPONIVEL, B.D1, B.D2, B.D3, B.D4, B.D5, B.D6, B.D7, B.D8, B.D9, B.D10, B.D11, B.D12, B.D13, B.D14, B.D15, B.D16 )  

----AND A.PRODUTO = '5.04287'  
  
--INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].WS_ESTOQUE_PRODUTOS_PWT(ID_CAMPANHA,LIBERAR_GRADE_WEB, PRODUTO, COR_PRODUTO, ESTOQUE, ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, DATA_PARA_TRANSFERENCIA,DT_INTEGRACAO,DT_EXCLUSAO )  
--SELECT B.ID_CAMPANHA,  
-- B.LIBERAR_GRADE_WEB, B.PRODUTO, B.COR_PRODUTO, B.SALDO_DISPONIVEL,   
-- D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, GETDATE() AS DATA_PARA_TRANSFERENCIA,   
-- DT_INTEGRACAO = CAST(GETDATE() AS SMALLDATETIME),DT_EXCLUSAO = CAST(GETDATE() AS SMALLDATETIME)  
--FROM GS_LOG_SALDO_WEB_WISE (NOLOCK) B   
-- LEFT JOIN [WISE_AZURE].[SOMA_LINX].[DBO].WS_ESTOQUE_PRODUTOS_PWT A ON A.PRODUTO = B.PRODUTO AND A.COR_PRODUTO = B.COR_PRODUTO  AND A.ID_CAMPANHA = A.ID_CAMPANHA 
--WHERE B.DATA_SALDO = CAST(GETDATE() AS DATE) AND A.PRODUTO IS NULL  
-- #GRUPOSOMA:02# FIM

-- #GRUPOSOMA:02#
BEGIN TRY
	INSERT INTO #TABELAS 
	SELECT 'WS_ESTOQUE_PRODUTOS','WS_ESTOQUE_PRODUTOS_PWT_'+CONVERT(VARCHAR(10),GETDATE(),112)+'_'+REPLACE(CONVERT(VARCHAR(10),GETDATE(),108),':','_'),0, NULL

	SET @TABELA = (SELECT TABELA_BKP FROM #TABELAS WHERE TABELA='WS_ESTOQUE_PRODUTOS')

	EXEC ('SELECT * INTO '+@TABELA+' FROM [Soma_Linx].[dbo].[WS_ESTOQUE_PRODUTOS]')	AT WISE_AZURE

	--EXEC ('TRUNCATE TABLE [SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS_PWT]') AT WISE_AZURE
	DELETE FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS] WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)
	--DELETE FROM OPENQUERY([WISE_AZURE],'SELECT * FROM [SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS_PWT]')
	--WHERE ID_CAMPANHA IN (SELECT DISTINCT ID_CAMPANHA FROM WS_PRODUTOS_INTERNET)

	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS] (ID_CAMPANHA,LIBERAR_GRADE_WEB, PRODUTO, COR_PRODUTO, ESTOQUE, ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, DATA_PARA_TRANSFERENCIA,DT_INTEGRACAO,DT_EXCLUSAO )  
	SELECT B.ID_CAMPANHA,  
	 B.LIBERAR_GRADE_WEB, B.PRODUTO, B.COR_PRODUTO, B.SALDO_DISPONIVEL,   
	 D1, D2, D3, D4, D5, D6, D7, D8, D9, D10, D11, D12, D13, D14, D15, D16, GETDATE() AS DATA_PARA_TRANSFERENCIA,   
	 DT_INTEGRACAO = @DT_SALDO ,DT_EXCLUSAO = NULL  
	FROM GS_LOG_SALDO_WEB_WISE (NOLOCK) B   
	WHERE B.DATA_SALDO = @DT_SALDO 

	--#GS:01.03#  --- INICIO ----
	SELECT DISTINCT A.PRODUTO, '99' AS ID_CAMPANHA
	INTO #WS_PRODUTOS_INTERNET
	FROM MB_PROD_EXTRA_WEB(NOLOCK) A
	INNER JOIN PRODUTOS (NOLOCK) B ON A.PRODUTO=B.PRODUTO AND B.REDE_LOJAS='29'

	--EXCLUSÃO DOS SALDOS DOS PRODUTOS DE PRONTA ENTREGA
	
	DELETE A 
	FROM [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS] AS A
	INNER JOIN #WS_PRODUTOS_INTERNET B ON A.PRODUTO=B.PRODUTO AND A.ID_CAMPANHA='99'
	
	--DELETE A
 --   FROM OPENQUERY([WISE_AZURE],'SELECT * FROM SOMA_LINX.DBO.WS_ESTOQUE_PRODUTOS_PWT') AS A
 --   INNER JOIN #WS_PRODUTOS_INTERNET B ON A.PRODUTO=B.PRODUTO AND A.ID_CAMPANHA='99'


	---PRODUTOS DO ME LEVA (PRONTA ENTREGA)
	INSERT INTO [WISE_AZURE].[SOMA_LINX].[DBO].[WS_ESTOQUE_PRODUTOS](LIBERAR_GRADE_WEB, PRODUTO, COR_PRODUTO, ESTOQUE, ES1, ES2, ES3, ES4, ES5, ES6, ES7, ES8, ES9, ES10, ES11, ES12, ES13, ES14, ES15, ES16, DATA_PARA_TRANSFERENCIA,ID_CAMPANHA )
	-- #GS:01.05#
	--SELECT '0' LIBERAR_GRADE_WEB, A.PRODUTO, A.COR_PRODUTO, A.TOTAL AS ESTOQUE, A.EX1, A.EX2, A.EX3, A.EX4, A.EX5, A.EX6, A.EX7, A.EX8, A.EX9, A.EX10, A.EX11, A.EX12, A.EX13, A.EX14, A.EX15, A.EX16, GETDATE() DATA_PARA_TRANSFERENCIA, '99' ID_CAMPANHA
	--FROM 
	--MB_PROD_EXTRA_WEB(NOLOCK) A
	--INNER JOIN PRODUTOS (NOLOCK) B ON A.PRODUTO=B.PRODUTO AND B.REDE_LOJAS='29'
	-- #GS:01.05#
	SELECT 
		'0' LIBERAR_GRADE_WEB, EXTRA.PRODUTO, EXTRA.COR_PRODUTO, CASE WHEN (EXTRA.ESTOQUE-isnull(VENDA.SALDO,0)) < 0 THEN 0 ELSE (EXTRA.ESTOQUE-isnull(VENDA.SALDO,0)) END AS ESTOQUE,
		CASE WHEN (EXTRA.EX1-isnull(VENDA.VO1,0)) < 0 THEN 0 ELSE (EXTRA.EX1-isnull(VENDA.VO1,0)) END AS S1,
		CASE WHEN (EXTRA.EX2-isnull(VENDA.VO2,0)) < 0 THEN 0 ELSE (EXTRA.EX2-isnull(VENDA.VO2,0)) END AS S2,
		CASE WHEN (EXTRA.EX3-isnull(VENDA.VO3,0)) < 0 THEN 0 ELSE (EXTRA.EX3-isnull(VENDA.VO3,0)) END AS S3,
		CASE WHEN (EXTRA.EX4-isnull(VENDA.VO4,0)) < 0 THEN 0 ELSE (EXTRA.EX4-isnull(VENDA.VO4,0)) END AS S4,
		CASE WHEN (EXTRA.EX5-isnull(VENDA.VO5,0)) < 0 THEN 0 ELSE (EXTRA.EX5-isnull(VENDA.VO5,0)) END AS S5,
		CASE WHEN (EXTRA.EX6-isnull(VENDA.VO6,0)) < 0 THEN 0 ELSE (EXTRA.EX6-isnull(VENDA.VO6,0)) END AS S6,
		CASE WHEN (EXTRA.EX7-isnull(VENDA.VO7,0)) < 0 THEN 0 ELSE (EXTRA.EX7-isnull(VENDA.VO7,0)) END AS S7,
		CASE WHEN (EXTRA.EX8-isnull(VENDA.VO8,0)) < 0 THEN 0 ELSE (EXTRA.EX8-isnull(VENDA.VO8,0)) END AS S8,
		CASE WHEN (EXTRA.EX9-isnull(VENDA.VO9,0)) < 0 THEN 0 ELSE (EXTRA.EX9-isnull(VENDA.VO9,0)) END AS S9,
		CASE WHEN (EXTRA.EX10-isnull(VENDA.VO10,0)) < 0 THEN 0 ELSE (EXTRA.EX10-isnull(VENDA.VO10,0)) END AS S10,
		CASE WHEN (EXTRA.EX11-isnull(VENDA.VO11,0)) < 0 THEN 0 ELSE (EXTRA.EX11-isnull(VENDA.VO11,0)) END AS S11,
		CASE WHEN (EXTRA.EX12-isnull(VENDA.VO12,0)) < 0 THEN 0 ELSE (EXTRA.EX12-isnull(VENDA.VO12,0)) END AS S12,
		CASE WHEN (EXTRA.EX13-isnull(VENDA.VO13,0)) < 0 THEN 0 ELSE (EXTRA.EX13-isnull(VENDA.VO13,0)) END AS S13,
		CASE WHEN (EXTRA.EX14-isnull(VENDA.VO14,0)) < 0 THEN 0 ELSE (EXTRA.EX14-isnull(VENDA.VO14,0)) END AS S14,
		CASE WHEN (EXTRA.EX15-isnull(VENDA.VO15,0)) < 0 THEN 0 ELSE (EXTRA.EX15-isnull(VENDA.VO15,0)) END AS S15,
		CASE WHEN (EXTRA.EX16-isnull(VENDA.VO16,0)) < 0 THEN 0 ELSE (EXTRA.EX16-isnull(VENDA.VO16,0)) END AS S16,
		GETDATE() DATA_PARA_TRANSFERENCIA, '99' ID_CAMPANHA
	FROM
	(
		SELECT A.PRODUTO, A.COR_PRODUTO, A.TOTAL AS ESTOQUE, 
		A.EX1, A.EX2, A.EX3, A.EX4, A.EX5, A.EX6, A.EX7, A.EX8, 
		A.EX9, A.EX10, A.EX11, A.EX12, A.EX13, A.EX14, A.EX15, A.EX16
		FROM 
		MB_PROD_EXTRA_WEB(NOLOCK) A
		INNER JOIN PRODUTOS (NOLOCK) B ON A.PRODUTO=B.PRODUTO AND B.REDE_LOJAS='29' --and a.produto='09.01.1671'--AND B.GRUPO_PRODUTO LIKE '%MOCHILA%'
	) AS EXTRA ---- Produtos Extras
	left JOIN 
	(
		SELECT B.PRODUTO, B.COR_PRODUTO,  SUM(A.QTDE_ORIGINAL) SALDO, 
		SUM(A.VO1) VO1, SUM(A.VO2) VO2, SUM(A.VO3) VO3, SUM(A.VO4) VO4, SUM(A.VO5) VO5, SUM(A.VO6) VO6, SUM(A.VO7) VO7, SUM(A.VO8) VO8,
		SUM(A.VO9) VO9, SUM(A.VO10) VO10, SUM(A.VO11) VO11, SUM(A.VO12) VO12, SUM(A.VO13) VO13, SUM(A.VO14) VO14, SUM(A.VO15) VO15, SUM(A.VO16) VO16 
		FROM 
		VENDAS_PRODUTO (NOLOCK) A
		INNER JOIN MB_PROD_EXTRA_WEB(NOLOCK) B ON A.PRODUTO=B.PRODUTO
		INNER JOIN PRODUTOS (NOLOCK) C ON A.PRODUTO=C.PRODUTO AND C.REDE_LOJAS='29' --AND C.GRUPO_PRODUTO LIKE '%MOCHILA%'
		INNER JOIN VENDAS (NOLOCK) D ON A.PEDIDO=D.PEDIDO AND D.EMISSAO >= '20191001'
		GROUP BY
		B.PRODUTO, B.COR_PRODUTO
	) AS VENDA ON EXTRA.PRODUTO=VENDA.PRODUTO AND EXTRA.COR_PRODUTO=VENDA.COR_PRODUTO ---- Produtos Vendidos
	--WHERE  VENDA.PRODUTO ='MC.03.0014'
	--ORDER BY 2
	
	-- #GS:01.05#
	--#GS:01.03# --- FINAL -----
	UPDATE #TABELAS SET PROCESSADO = 1 WHERE TABELA_BKP = @TABELA

END TRY
BEGIN CATCH
	SELECT ERROR_MESSAGE()
	UPDATE #TABELAS SET PROCESSADO = 0, ERROR=ERROR_MESSAGE() WHERE TABELA_BKP = @TABELA
END CATCH

-- LIMPA AS TABELAS QUE TIVERAO SUCESSO NA INTEGRAÇÃO
SET @TABELA=''

DECLARE XCURSOR CURSOR FAST_FORWARD FOR
	SELECT RTRIM(LTRIM(TABELA_BKP)) AS TABELA_DELETAR FROM #TABELAS WHERE PROCESSADO = 1

OPEN XCURSOR
FETCH NEXT FROM XCURSOR INTO @TABELA

WHILE @@FETCH_STATUS = 0
BEGIN
	EXEC ('DROP TABLE [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE
	FETCH NEXT FROM XCURSOR INTO @TABELA
END

CLOSE XCURSOR
DEALLOCATE XCURSOR


DECLARE XCURSOR CURSOR FAST_FORWARD FOR
	SELECT RTRIM(LTRIM(TABELA_BKP)) AS TABELA_DELETAR, TABELA FROM #TABELAS WHERE PROCESSADO = 0

OPEN XCURSOR
FETCH NEXT FROM XCURSOR INTO @TABELA, @TABELA_OLD

WHILE @@FETCH_STATUS = 0
BEGIN
	--- LIMPO A TABELA ORIGINAL
	EXEC ('TRUNCATE TABLE [Soma_Linx].[dbo].['+@TABELA_OLD+']')	AT WISE_AZURE
	--- VOLTO O BACKUP
	EXEC ('INSERT INTO [Soma_Linx].[dbo].['+@TABELA_OLD+'] SELECT * FROM [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE
	--- APAGO A TABELA TEMPORARIA
	EXEC ('DROP TABLE [Soma_Linx].[dbo].['+@TABELA+']')	AT WISE_AZURE

	FETCH NEXT FROM XCURSOR INTO @TABELA, @TABELA_OLD
END

CLOSE XCURSOR
DEALLOCATE XCURSOR

DROP TABLE #TABELAS
