// <auto-generated />
using System;
using BlueprintOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlueprintOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BlueprintOSDbContext))]
    [Migration("20260903204832_AddRawCadastroApoioSnapshotsB3Bloco5A")]
    partial class AddRawCadastroApoioSnapshotsB3Bloco5A
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlueprintOS.Domain.Identity.AlcadaAprovacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AprovadorPerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AprovadorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CentroCustoMetadadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Criterio")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId");

                    b.ToTable("AlcadasAprovacao", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.BootstrapEstado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Concluido")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid?>("UsuarioAdministradorSeniorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("BootstrapEstado", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Concluido = false
                        });
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.BootstrapSessao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailCandidato")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdentificadorHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UsadaEm")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorHash")
                        .IsUnique();

                    b.ToTable("BootstrapSessoes", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.CentroCustoMetadado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtivoNoMaisCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescricaoMaisCompras")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp")
                        .IsUnique()
                        .HasDatabaseName("IX_CentrosCustoMetadados_CodigoErp");

                    b.ToTable("CentrosCustoMetadados", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.CentroCustoUnidadeAlocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CentroCustoMetadadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Padrao")
                        .HasColumnType("bit");

                    b.Property<Guid>("UnidadeAlocacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CentroCustoMetadadoId")
                        .IsUnique()
                        .HasDatabaseName("IX_CentrosCustoUnidadesAlocacao_CentroCustoMetadadoId_Padrao")
                        .HasFilter("[Padrao] = 1");

                    b.HasIndex("UnidadeAlocacaoId");

                    b.HasIndex("CentroCustoMetadadoId", "UnidadeAlocacaoId")
                        .IsUnique();

                    b.ToTable("CentrosCustoUnidadesAlocacao", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.CodigoVerificacaoOtp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmailCandidato")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmailCandidato")
                        .IsUnique()
                        .HasDatabaseName("IX_CodigosVerificacaoOtp_EmailCandidato_Pendente")
                        .HasFilter("[Status] = 0 AND [EmailCandidato] IS NOT NULL");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_CodigosVerificacaoOtp_UsuarioId_Pendente")
                        .HasFilter("[Status] = 0 AND [UsuarioId] IS NOT NULL");

                    b.HasIndex("UsuarioId", "Status");

                    b.ToTable("CodigosVerificacaoOtp", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ConfiguracaoErp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ParametrosConexaoProtegidos")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("SistemaErp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesErp", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ConfiguracaoNotificacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("EmailAtivado")
                        .HasColumnType("bit");

                    b.Property<string>("EmailRemetente")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NomeRemetente")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId")
                        .IsUnique();

                    b.ToTable("ConfiguracoesNotificacao", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ContaContabilMetadado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtivoNoMaisCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescricaoMaisCompras")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp")
                        .IsUnique()
                        .HasDatabaseName("IX_ContasContabeisMetadados_CodigoErp");

                    b.ToTable("ContasContabeisMetadados", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.FeatureFlagUnidadeNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FeatureFlagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FeatureFlagId", "UnidadeNegocioId")
                        .IsUnique();

                    b.ToTable("FeatureFlagsUnidadesNegocio", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.FilialMetadado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtivoNoMaisCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescricaoMaisCompras")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId", "CodigoErp")
                        .IsUnique()
                        .HasDatabaseName("IX_FiliaisMetadados_UnidadeNegocioId_CodigoErp");

                    b.ToTable("FiliaisMetadados", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.IdentityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DominiosAutorizadosCsv")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasDefaultValue("");

                    b.Property<string>("ParametrosProtegidos")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId");

                    b.ToTable("IdentityProviders", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ItemFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContaContabilCodigoErp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("OrigemInformacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("MaisCompras");

                    b.Property<DateTimeOffset?>("UltimaAlteracaoErp")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("UltimaAlteracaoLocalEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UnidadeMedidaCodigoErp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_ItensFiscais_Codigo");

                    b.HasIndex("UnidadeNegocioId")
                        .HasDatabaseName("IX_ItensFiscais_UnidadeNegocioId");

                    b.ToTable("ItensFiscais", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ItemFiscalReferenciaFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoItemFornecedor")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemFiscalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId", "CodigoItemFornecedor")
                        .IsUnique()
                        .HasDatabaseName("IX_ItensFiscaisReferenciasFornecedor_FornecedorId_CodigoItemFornecedor");

                    b.HasIndex("ItemFiscalId", "FornecedorId")
                        .IsUnique()
                        .HasDatabaseName("IX_ItensFiscaisReferenciasFornecedor_ItemFiscalId_FornecedorId");

                    b.ToTable("ItensFiscaisReferenciasFornecedor", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.OtpRequestThrottle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailNormalizado")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset>("JanelaIniciadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SolicitacoesNaJanela")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UltimaSolicitacaoEm")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalizado")
                        .IsUnique();

                    b.ToTable("OtpRequestThrottles", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Parametro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique()
                        .HasDatabaseName("IX_Parametros_Chave_Global")
                        .HasFilter("[UnidadeNegocioId] IS NULL");

                    b.HasIndex("Chave", "UnidadeNegocioId")
                        .IsUnique()
                        .HasFilter("[UnidadeNegocioId] IS NOT NULL");

                    b.ToTable("Parametros", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Perfis_UnidadeNegocioId_Nome");

                    b.ToTable("Perfis", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.PerfilPermissao", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PerfilId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("PerfisPermissoes", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Permissao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Permissoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000001"),
                            Codigo = "UnidadeNegocio.Gerenciar",
                            Descricao = "Criar, editar e inativar Unidades de Negócio"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000002"),
                            Codigo = "Usuario.Gerenciar",
                            Descricao = "Criar, editar, ativar/inativar usuários e vincular Perfis e Centros de Custo"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000003"),
                            Codigo = "Perfil.Gerenciar",
                            Descricao = "Criar, editar e ativar/inativar Perfis e suas permissões"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000004"),
                            Codigo = "Filial.Gerenciar",
                            Descricao = "Ativar/inativar Filiais no +Compras e manter a Descrição +Compras"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000005"),
                            Codigo = "CentroCusto.Gerenciar",
                            Descricao = "Ativar/inativar Centros de Custo no +Compras e manter a Descrição +Compras"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000006"),
                            Codigo = "UnidadeAlocacao.Gerenciar",
                            Descricao = "Criar, editar e ativar/inativar Unidades de Alocação"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000007"),
                            Codigo = "ConfiguracaoErp.Gerenciar",
                            Descricao = "Configurar a integração de ERP por Unidade de Negócio"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000008"),
                            Codigo = "Sistema.Gerenciar",
                            Descricao = "Acessar Administração do Sistema (integrações, monitor, filas, logs, saúde)"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000009"),
                            Codigo = "Fornecedor.Criar",
                            Descricao = "Cadastrar novo fornecedor"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000a"),
                            Codigo = "Fornecedor.Editar",
                            Descricao = "Atualizar dados de fornecedor"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000b"),
                            Codigo = "Fornecedor.Aprovar",
                            Descricao = "Aprovar divergências de enriquecimento de fornecedor"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000c"),
                            Codigo = "Pedido.Criar",
                            Descricao = "Criar pedido de compra"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000d"),
                            Codigo = "Pedido.Aprovar",
                            Descricao = "Aprovar pedido de compra"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000e"),
                            Codigo = "Pedido.Cancelar",
                            Descricao = "Cancelar pedido de compra"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-00000000000f"),
                            Codigo = "Workflow.Gerenciar",
                            Descricao = "Criar, editar e ativar/inativar Regras de Workflow por Unidade de Negócio"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000010"),
                            Codigo = "Alcada.Gerenciar",
                            Descricao = "Criar, editar e ativar/inativar Alçadas de Aprovação por Unidade de Negócio"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000011"),
                            Codigo = "Orcamento.Gerenciar",
                            Descricao = "Criar, editar e ativar/inativar Regras Orçamentárias por Unidade de Negócio"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000012"),
                            Codigo = "ConhecimentoLinx.Gerenciar",
                            Descricao = "Registrar descobertas/inferências e validar conhecimento dos Agents Especialistas Linx"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000013"),
                            Codigo = "ConhecimentoLinx.Aprovar",
                            Descricao = "Promover conhecimento dos Agents Especialistas Linx a 'Aprovado'"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000014"),
                            Codigo = "ContaContabil.Gerenciar",
                            Descricao = "Ativar/inativar Contas Contábeis no +Compras e manter a Descrição +Compras"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000015"),
                            Codigo = "UnidadeMedida.Gerenciar",
                            Descricao = "Ativar/inativar Unidades de Medida no +Compras e manter a Descrição +Compras"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000016"),
                            Codigo = "ItemFiscal.Visualizar",
                            Descricao = "Consultar o cadastro de Item Fiscal"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000017"),
                            Codigo = "ItemFiscal.Criar",
                            Descricao = "Cadastrar novo Item Fiscal"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000018"),
                            Codigo = "ItemFiscal.Editar",
                            Descricao = "Editar Item Fiscal existente"
                        },
                        new
                        {
                            Id = new Guid("b1a5c4e0-0001-4a10-9f01-000000000019"),
                            Codigo = "ItemFiscal.Inativar",
                            Descricao = "Ativar/inativar Item Fiscal no +Compras"
                        });
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Raw.RawLinxCentroCustoRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("DescricaoErp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("InativoErp")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp");

                    b.ToTable("RAW_LinxCentrosCustoSnapshot", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Raw.RawLinxContaContabilRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DescricaoErp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("InativoErp")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp");

                    b.ToTable("RAW_LinxContasContabeisSnapshot", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Raw.RawLinxUnidadeMedidaRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DescricaoErp")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool?>("InativoErp")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp");

                    b.ToTable("RAW_LinxUnidadesMedidaSnapshot", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.RegraOrcamentaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CentroCustoMetadadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ValorLimite")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId", "CentroCustoMetadadoId", "Periodo");

                    b.ToTable("RegrasOrcamentarias", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.RegraWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("TipoProcesso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId");

                    b.ToTable("RegrasWorkflow", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.SessaoAutenticacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AbsoluteExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdentificadorHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdentificadorHash")
                        .IsUnique();

                    b.ToTable("SessoesAutenticacao", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UnidadeAlocacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId", "Nome")
                        .IsUnique();

                    b.ToTable("UnidadesAlocacao", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UnidadeMedidaMetadado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AtivoNoMaisCompras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DescricaoMaisCompras")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoErp")
                        .IsUnique()
                        .HasDatabaseName("IX_UnidadesMedidaMetadados_CodigoErp");

                    b.ToTable("UnidadesMedidaMetadados", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UnidadeNegocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("UnidadesNegocio", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TodosCentrosCusto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UsuarioCentroCusto", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CentroCustoCodigoErp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UsuarioId", "CentroCustoCodigoErp");

                    b.ToTable("UsuariosCentrosCusto", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UsuarioPerfil", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("UsuariosPerfis", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Integrations.Occurrences.IntegrationOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ContextoTecnico")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginRecordKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("Dataset", "Status");

                    b.HasIndex("ExecutionId", "Dataset", "Stage", "Code", "OriginRecordKey")
                        .IsUnique()
                        .HasDatabaseName("IX_IntegrationOccurrences_Dedup")
                        .HasFilter("[OriginRecordKey] IS NOT NULL");

                    b.ToTable("IntegrationOccurrences", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Knowledge.Linx.LinxKnowledgeEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Ator")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("EntradaAnteriorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Especialista")
                        .HasColumnType("int");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Proveniencia")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<Guid>("VersaoRaizId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UnidadeNegocioId");

                    b.HasIndex("VersaoRaizId");

                    b.HasIndex("Especialista", "Categoria");

                    b.ToTable("LinxConhecimentoEntradas", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.CategoriaFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CategoriasFornecedor", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000001"),
                            Ativo = true,
                            Codigo = "MATERIA_PRIMA",
                            Descricao = "Matéria-Prima"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000002"),
                            Ativo = true,
                            Codigo = "EMBALAGEM",
                            Descricao = "Embalagem"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000003"),
                            Ativo = true,
                            Codigo = "SERVICOS_GERAIS",
                            Descricao = "Serviços Gerais"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000004"),
                            Ativo = true,
                            Codigo = "TRANSPORTE_LOGISTICA",
                            Descricao = "Transporte e Logística"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000005"),
                            Ativo = true,
                            Codigo = "MARKETING_PUBLICIDADE",
                            Descricao = "Marketing e Publicidade"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000006"),
                            Ativo = true,
                            Codigo = "TECNOLOGIA_INFORMACAO",
                            Descricao = "Tecnologia da Informação"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000007"),
                            Ativo = true,
                            Codigo = "MANUTENCAO_FACILITIES",
                            Descricao = "Manutenção e Facilities"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000008"),
                            Ativo = true,
                            Codigo = "CONSULTORIA",
                            Descricao = "Consultoria"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-000000000009"),
                            Ativo = true,
                            Codigo = "EQUIPAMENTOS",
                            Descricao = "Equipamentos"
                        },
                        new
                        {
                            Id = new Guid("8a9f1b1a-0001-4a00-9a00-00000000000a"),
                            Ativo = true,
                            Codigo = "OUTROS",
                            Descricao = "Outros"
                        });
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.ErroSincronizacaoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FornecedorIdentificacao")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SincronizacaoFornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StackTrace")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DataHora");

                    b.HasIndex("SincronizacaoFornecedorId");

                    b.ToTable("ErrosSincronizacoesFornecedores", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Beneficiador")
                        .HasColumnType("bit");

                    b.Property<string>("BusinessUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CategoriasFornecimento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CnaePrincipalCodigo")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("CnaePrincipalDescricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Cnpj_Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CodigoMunicipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicaoPagamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CondicaoPagamentoDominioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaContabil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Ddd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigitosConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("EmailFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErpFornecedorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ErpSistema")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ForneceConsumo")
                        .HasColumnType("bit");

                    b.Property<bool>("ForneceMateriais")
                        .HasColumnType("bit");

                    b.Property<bool>("ForneceProdutos")
                        .HasColumnType("bit");

                    b.Property<bool>("ForneceServicos")
                        .HasColumnType("bit");

                    b.Property<string>("HashDadosSincronizaveis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Licenciado")
                        .HasColumnType("bit");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MensagemErroSincronizacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigemInformacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrigemUltimaAlteracao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RegimeFiscal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScoreIA")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("SimplesNacional")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StatusSincronizacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubtipoFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SubtipoFornecedorDominioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("TemporaryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoFornecedor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TipoFornecedorDominioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoPessoa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj_Cpf")
                        .IsUnique();

                    b.HasIndex("RazaoSocial");

                    b.HasIndex("ErpSistema", "ErpFornecedorId")
                        .IsUnique()
                        .HasDatabaseName("IX_Fornecedores_ErpSistema_ErpFornecedorId")
                        .HasFilter("[ErpFornecedorId] IS NOT NULL");

                    b.ToTable("Fornecedores", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorCnpjConsultaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cnpj_Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("DataConsulta")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErpSistema")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("FonteConsulta")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("PayloadBrutoDescartadoPorTamanho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PayloadBrutoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoErro")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("Usuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("DataConsulta");

                    b.HasIndex("BusinessUnit", "Cnpj_Cpf", "DataConsulta");

                    b.ToTable("FornecedoresCnpjConsultas", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorDescoberto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("CodigoFornecedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("DescobertoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid?>("TemporaryUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CodigoItem");

                    b.HasIndex("DescobertoEm");

                    b.ToTable("FornecedoresDescobertos", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorDominioErp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CodigoERP")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ErpSistema")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("UltimaSincronizacaoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "BusinessUnit", "ErpSistema", "CodigoERP")
                        .IsUnique();

                    b.ToTable("FornecedoresDominiosErp", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorEnriquecimentoAnalise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Cnpj_Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<Guid?>("ConsultaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("DataHora")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ErpSistema")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Fonte")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Usuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ValorNovo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("FornecedorId", "Campo", "DataHora");

                    b.ToTable("FornecedoresEnriquecimentoAnalises", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorLinxVinculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CodigoErp")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DataParaTransferencia")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ErpSistema")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("InativoCadastroCliFor")
                        .HasColumnType("bit");

                    b.Property<bool>("InativoFornecedores")
                        .HasColumnType("bit");

                    b.Property<string>("NomeClifor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Principal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ErpSistema", "CodigoErp")
                        .IsUnique()
                        .HasDatabaseName("IX_FornecedorLinxVinculos_ErpSistema_CodigoErp");

                    b.HasIndex(new[] { "FornecedorId" }, "IX_FornecedorLinxVinculos_FornecedorId");

                    b.HasIndex(new[] { "FornecedorId" }, "IX_FornecedorLinxVinculos_FornecedorId_PrincipalAtivo")
                        .IsUnique()
                        .HasFilter("[Principal] = 1 AND [InativoFornecedores] = 0 AND [InativoCadastroCliFor] = 0");

                    b.ToTable("FornecedorLinxVinculos", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.FornecedorSincronizacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("CamposAlterados")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decisao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Destino")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Direcao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DuracaoMs")
                        .HasColumnType("int");

                    b.Property<string>("ErpFornecedorId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ErpSistema")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("ExecutadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashAntes")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("HashDepois")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Origem")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Tentativa")
                        .HasColumnType("int");

                    b.Property<string>("TimestampComprasNormalizado")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TimestampComprasOriginal")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TimestampErpNormalizado")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TimestampErpOriginal")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessUnit", "ErpSistema", "ErpFornecedorId", "ExecutadaEm");

                    b.ToTable("FornecedoresSincronizacoes", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.Raw.LinxDatasetLoadState", b =>
                {
                    b.Property<string>("Dataset")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("BaselineExecucaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("BaselineHomologadaEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("CargaFullInicialValidada")
                        .HasColumnType("bit");

                    b.Property<bool>("IncrementalLiberado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UltimaExecucaoValidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UltimoWatermarkValido")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Dataset");

                    b.ToTable("LinxDatasetLoadState", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.Raw.RawLinxFornecedorSnapshotExecucao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Completa")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ConcluidoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Dataset")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Erro")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("IniciadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IsolamentoUtilizado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("LinhasGravadas")
                        .HasColumnType("bigint");

                    b.Property<long>("LinhasLidas")
                        .HasColumnType("bigint");

                    b.Property<string>("Modo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReconciliacaoStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("ReconciliadoEm")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WatermarkFinal")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("WatermarkInicial")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Dataset", "IniciadoEm");

                    b.HasIndex("Dataset", "Modo", "ReconciliacaoStatus");

                    b.ToTable("RAW_LinxFornecedoresSnapshotExecucoes", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.Raw.RawLinxFornecedorSnapshotRegistro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clifor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CnpjCpf")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoFornecedor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("InativoCadastroCliFor")
                        .HasColumnType("bit");

                    b.Property<bool>("InativoFornecedores")
                        .HasColumnType("bit");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("TipoPessoa")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UltimaAlteracao")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("CnpjCpf");

                    b.ToTable("RAW_LinxFornecedoresSnapshot", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.SincronizacaoFornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessUnit")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset?>("DataFim")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DataInicio")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("JustificativaEncerramento")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SistemaOrigem")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("TempoExecucaoMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalAtualizado")
                        .HasColumnType("int");

                    b.Property<int>("TotalConsultado")
                        .HasColumnType("int");

                    b.Property<int>("TotalErro")
                        .HasColumnType("int");

                    b.Property<int>("TotalIncluido")
                        .HasColumnType("int");

                    b.Property<int>("TotalSemAlteracao")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeNegocioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UsuarioRecuperacaoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UnidadeNegocioId");

                    b.HasIndex("BusinessUnit", "SistemaOrigem", "DataInicio");

                    b.ToTable("SincronizacoesFornecedores", (string)null);
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.CentroCustoUnidadeAlocacao", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Identity.CentroCustoMetadado", null)
                        .WithMany()
                        .HasForeignKey("CentroCustoMetadadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueprintOS.Domain.Identity.UnidadeAlocacao", null)
                        .WithMany()
                        .HasForeignKey("UnidadeAlocacaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.ItemFiscalReferenciaFornecedor", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Procurement.Suppliers.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueprintOS.Domain.Identity.ItemFiscal", null)
                        .WithMany()
                        .HasForeignKey("ItemFiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.PerfilPermissao", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Identity.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueprintOS.Domain.Identity.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UsuarioCentroCusto", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Identity.UsuarioPerfil", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Identity.Perfil", null)
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueprintOS.Domain.Identity.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.ErroSincronizacaoFornecedor", b =>
                {
                    b.HasOne("BlueprintOS.Domain.Procurement.Suppliers.SincronizacaoFornecedor", null)
                        .WithMany("Erros")
                        .HasForeignKey("SincronizacaoFornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlueprintOS.Domain.Procurement.Suppliers.SincronizacaoFornecedor", b =>
                {
                    b.Navigation("Erros");
                });
#pragma warning restore 612, 618
        }
    }
}
